name: odds_league
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  table_calendar: ^3.0.3
  url_launcher: ^6.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
